apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-client
  template:
    metadata:
      labels:
        app: flink-client
    spec:
      containers:
        - name: client
          image: us-phoenix-1.ocir.io/idxglh0bz964/flink-demo:1.12.2-scala_2.12-java11
          imagePullPolicy: Always
          args: ["sleep", "86400"]
      imagePullSecrets:
        - name: ocirsecret